### ISSUE TITLE
Problems when installed as a `.sublime-package` file

### ISSUE THREAD

**Issue by keith-hall** [kylebebak/Requester#1]
I saw this at https://github.com/wbond/package_control_channel/pull/6294 and was interested to try it. Unfortunately, there seems to be a few problems at the moment. (I like the descriptiveness of your PR on the PC channel btw :))

### Summary

When Requester is installed via Package Control, trying to use the `Requester: Show Tutorial` item in the Command Palette throws lots of errors in the ST console instead of showing the tutorial.

### Expected behavior

The functionality described in the readme would work, for example, the tutorial.

### Actual behavior

Nothing happens (except the traceback) when trying to run the tutorial.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "other_commands in C:\Users\Keith\AppData\Roaming\Sublime Text 3\Installed Packages\Requester.sublime-package", line 42, in run
  File "./python3.3/shutil.py", line 109, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Keith\\AppData\\Roaming\\Sublime Text 3\\Packages\\Requester\\docs\\_tutorial.md'
```

### Steps to reproduce

1. Open ST
1. Open Command Palette
1. Type `PC: AR`
1. Select `Package Control: Add Repository`
1. Paste in `https://github.com/kylebebak/Requester` and press <kbd>Enter</kbd>
1. Open Command Palette
1. Select `Package Control: Install Package`
1. Type `Requester`
1. Open Command Palette
1. Type `rtut` and select `Requester: Show Tutorial`
1. Notice nothing happens. Open the ST console and see the traceback

### Tips

Maybe add a [`.no-sublime-package` file](https://packagecontrol.io/docs/submitting_a_package#Step_5) to fix this problem, or ideally, find a way to make it work in a package :)

### Environment

* Operating system and version: Windows 7 x64
* Sublime Text Build: 3131
* Package Control version: 3.2.1
* Requester version: 1.2.0

**Comment by kylebebak** [comment]
@keith-hall 

Thanks for the detailed issue, I'm working on this right now!

**Comment by kylebebak** [comment]
@keith-hall 

Ok, I created a new release that fixes this bug, at least on my machine.

I would love to hear what you think of the package!

**Comment by keith-hall** [comment]
Thanks @kylebebak :) when I run the Show Tutorial command now, it opens 👍 but with an error:

```
---------------------------
Sublime Text
---------------------------
Error loading syntax file "Packages/MarkdownEditing/Markdown.tmLanguage": Unable to open Packages/MarkdownEditing/Markdown.tmLanguage
---------------------------
OK   
---------------------------
```

Maybe you should detect if the `MarkdownEditing` package is installed before setting the syntax? And set to the default one if not - it's been vastly improved recently but doesn't highlight code in fenced code blocks yet.

What platform are you testing on, out of interest? I'm getting an error when I follow the tutorial, and execute `Requester: Run Requests` from the Command Palette when my caret is on the url in the `requests.get('https://jsonplaceholder.typicode.com/albums')` line:

```Traceback (most recent call last):
  File "D:\Software\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "common in C:\Users\Keith\AppData\Roaming\Sublime Text 3\Installed Packages\Requester.sublime-package", line 26, in run
  File "common in C:\Users\Keith\AppData\Roaming\Sublime Text 3\Installed Packages\Requester.sublime-package", line 43, in get_env
  File "<string>", line 4, in <module>
AttributeError: 'module' object has no attribute 'cookies'
```

**Comment by kylebebak** [comment]
@keith-hall 

I didn't realize there was a default Markdown syntax, I'll fall back to that one if MarkdownEditing isn't installed.

I'm on OSX, build 3126. It looks like referencing `requests.cookies` is raising the `AttributeError`. This happened to me at one point, but the problem was resolved when I uninstalled and reinstalled Requester.

As far as I understand this shouldn't be an issue, because the [requests](https://github.com/packagecontrol/requests) library is a [dependency](https://packagecontrol.io/docs/dependencies) of my package.

This, in theory, should mean that I can use `import requests` in Requester. And `requests.cookies` shouldn't raise an AttributeError. I'm not sure what's going on here.

**Comment by keith-hall** [comment]
After running `Package Control: Satisfy Dependencies` and restarting ST it's working :) sorry, I should have thought of that myself. I wonder why the restart is needed... Maybe it'd be a good idea to mention it in the install notes, what do you think?

I can assure you that ST has a default Markdown syntax, I have worked on it myself: https://github.com/sublimehq/Packages/blob/master/Markdown/Markdown.sublime-syntax

After having had a little play around, I can see that this package is super useful - thanks for taking the time to build it :)
If you're interested, and I get time, I might like to submit a PR to get the syntax highlighting a bit smarter, and color the HTTP headers nicely etc :)

**Comment by kylebebak** [comment]
@keith-hall 

Hey Keith,

It would definitely be a good idea to mention it, tomorrow I'm going to push a release with some nice changes and close this issue:

- add instructions to use `Package Control: Satisfy Dependencies`, and a pop suggesting that user do this if one of these `AttributeError`s is raised because `requests` isn't being imported properly
- allowing requests to be executed from a view that hasn't yet been saved
- allowing users to specify path to env file with absolute or relative path
- assume you execute a request that matches a request in an open tab: instead of closing and reopening this tab, which might change its position relative to other tabs, simply reset the content in the matching tab when the response returns

I would be very grateful if you wanted to improve syntax highlighting, the HTTP headers, or anything else that could use some work =)

**Comment by keith-hall** [comment]
Sounds great Kyle! :) I just noticed a small typo you could fix in the next release too, to make this package look even more professional ;) https://github.com/kylebebak/Requester/blob/6803912917cd1d633e520fd367b156c4348ad9c9/messages/install.txt#L6
> Re**s**quester

**Comment by kylebebak** [comment]
Oops =)

**Comment by kylebebak** [comment]
@keith-hall 

I uploaded release 1.3.0 which includes the features in my previous comment.

There is information in the README, the tutorial, and the install message advising users to run `Package Control: Satisfy Dependencies` if nothing is working.

Also, the default Markdown syntax is used as a fallback if MardownEditing syntax isn't found. Neither of these syntaxes causes an error popup to appear if it's not present.

I'm going to close this issue, and let AlexKvazos the package is ready. Thanks a lot!
